from pathlib import Path
import json
base=Path(__file__).resolve().parent;root=base.parents[1]
d=json.loads((base/'history.json').read_text(encoding='utf-8'))
out=root/'scope-and-sequence';plans=out/'history-projects';plans.mkdir(exist_ok=True)
res={r['id']:r for r in d['resources']}
def cell(v):return str(v).replace('|','/').replace('\n','<br>')
def table(h,rows):return '\n'.join(['| '+' | '.join(h)+' |','| '+' | '.join(['---']*len(h))+' |']+['| '+' | '.join(cell(v) for v in r)+' |' for r in rows])
def links(ids):return '; '.join(f"[{res[i]['title']}]({res[i]['url']})" for i in ids)
def ll(l,p):return f"[{l['id']}](history-projects/{p['slug']}.md#{l['id'].lower()})"
course=['# Grade 6 history scope and sequence',f"Updated {d['date']}. {d['status']}",
'## Course overview','Students investigate how societies formed, compare their institutions and beliefs, connect inventions with historical context, and explain Rome’s transformation using evidence.',
table(['Item','Plan'],[['Schedule',d['scope']],['National basis','NCSS National Curriculum Standards (2010), public ten-theme framework; C3 Framework (2013), selected Grades 6–8 indicators. Theme labels NCSS-T1–T10 are local navigation labels, not official performance codes.'],['Content allocation','Early humans and Mesopotamia → Egypt/Nubia, Israel and India → China and Greece → Rome through western collapse and eastern continuation. Societies overlap in time; the project order is not a single worldwide succession.'],['Tennessee check','2024 adoption / 2027–28 implementation. 62 content standards and six recurring practices reviewed; 6.39 chronology remains Unverified.'],['Workbook','[Grade 6 history workbook](<../6th Grade/Grade_6_History_Curriculum_Standards.xlsx>)'],['Input','[Completed Grade 6 handoff](<../6th Grade/Grade_6_Project_Handoff.md>); revised H3 is authoritative.'],['Outside work and enrollment','No required homework. Planning assumption: 24 learners/six teams; confirm actual calendar, learner needs and observation capacity.'],['Completion boundary','This is a term scope and sequence (Steps 1–4). Project documents are outlines, not detailed Step 5 teaching plans. Materials, exact excerpts, model responses and classroom trials remain.']]),
'## Projects at a glance',table(['Project','What students do','Final product / experience','Reading / resources','Assessments'],[[f"[{p['id']} {p['title']}](history-projects/{p['slug']}.md)",p['glance'],p['product'],'Short attributed context readings, dated maps and selected source cards; teacher sources in the register.','Private source/knowledge checks, revised individual explanation and a separately reviewed team product.'] for p in d['projects']]),
'## Progression and assessment',table(['Strand','Sequence'],[['Inquiry','Guided sourcing/inference → contextualized comparison → distinguish historical evidence and modern measurement → increasingly independent corroboration and multi-cause argument.'],['Geography and chronology','Local settlement map → overlapping society maps/timelines → separate China/Greece exchange networks → changing Roman boundaries and eastern continuation.'],['Institutions and economy','Surplus, specialization and city authority → social roles/belief institutions → philosophical/state support and citizenship → republic/empire, infrastructure and political/economic pressures.'],['Source reasoning','Maker/date/place/type → purpose/perspective and missing voices → evidence limits and transmission claims → competing interpretations and relative causes.'],['Assessment','Practice and drafts get specific feedback. Final individual responses and fresh-source checks establish each learner’s reasoning separately from group polish. No invented weights, scores or cutoffs.']])]
for p in d['projects']:
 course += [f"## {p['id']} — {p['title']}",f"**Question:** {p['question']}", '**Lasting understandings:** '+' '.join(p['understandings']),
 table(['Course week','Priority learning','Individual / group blocks','Evidence and feedback'],[[4*(p['n']-1)+w,p['lessons'][2*(w-1)]['content']+' '+p['lessons'][2*(w-1)+1]['content'],ll(p['lessons'][2*(w-1)],p)+': '+p['lessons'][2*(w-1)]['title']+'; '+ll(p['lessons'][2*(w-1)+1],p)+': '+p['lessons'][2*(w-1)+1]['title'],p['lessons'][2*(w-1)+1]['evidence']+' '+p['lessons'][2*(w-1)+1]['support']] for w in range(1,5)])]
course += ['## Workload review and next-stage decisions',
table(['Pair / issue','Planning correction','Still to verify'],[['H2-W3: India','Two short religion profiles plus a city plan/achievement strip. Caption polish moves to W4-I. Everyone studies all societies.','Exact reading load, vocabulary and individual component checks in Step 5.'],['H3-W2: Greece','Short conflict/philosophy cards, reuse maps/timeline, one later water-timer investigation; no gear reconstruction.','Whether history instruction, source reading and individual checks fit 180 minutes; move production polish if needed.'],['H3-W3: timer','One teacher-prepared device, three short repeat trials, supplied shadow data, analysis and cleanup. No second practical investigation.','Clock-source access, exact procedure, equipment and accessible participation.'],['H4 council','Evidence discussion about actual history, with individually recorded explanations; no outcome game.','Six-team presentation/observation schedule and fresh-source checks.']]),
'## Assumptions and unresolved needs',table(['Area','Action'],d['needs']),
'## National framework and inquiry routes','These are selected contributions within an ancient-history term. The public NCSS themes organize content; the full middle-grades performance expectations are not individually certified. C3 indicators describe end-of-band capacities and guide recurring practice; this Grade 6 term does not claim the complete Grades 6–8 framework. Remaining modern civics/economics/geography and informed-action work needs schoolwide allocation.',
table(['Local theme label','NCSS theme','Specified learning destinations'],[[t['id'],t['title'],', '.join(t['routes'])] for t in d['themes']]),
table(['C3 indicator','Interpretive learning summary','Primary routes','Supporting routes'],[[n['id'],n['learning'],', '.join(n['primary_routes']) or 'Supporting only',', '.join(n['support_routes']) or 'None separately assigned'] for n in d['national']]),
'## Tennessee content-compliance appendix','The official content wording below is extracted from PDF pages 83–98; source PDF controls. SSP summaries are interpretive, recurring across the term. Covered in plan means a route exists in the outline, with exact component evidence still to verify in Step 5. It does not establish mastery, operating compliance or accreditation.',
table(['TN requirement/component','Lesson and individual evidence destinations','Status','Action'],[[t['id']+' — '+t['source_text'],', '.join(t['routes']),t['status'],t['action']] for t in d['tn']]),
'## Recovered assignment traceability',table(['Project','Recovered home IDs','Recurrence IDs','Interpretation'],[[p['id'],', '.join(f'SS.{i:02}' for i in p['home']),', '.join(f'SS.{i:02}' for i in p['recur']) or 'Prior-grade foundations','Historical bundled learning retained. These local IDs are not the official TN 6.xx or national identifiers. SSP.01–06 recur throughout.'] for p in d['projects']]),
'## Source and resource register',table(['Resource','Assigned use','Readiness'],[[f"{r['id']} — [{r['title']}]({r['url']})",r['selection'],r['status']] for r in d['resources']]),
'## Detailed planning handoff','Step 5 develops full procedures, exact source metadata/excerpts, concrete prompts, individual component assessments, task-specific models/support and fitted clocks from these 32 outlines. Step 6 produces student materials, verifies history/data/access, calibrates answers and trials the busiest pairs. Use descriptive criteria for accuracy, relevant evidence, reasoning, context, limits and substantive revision. Accreditation review remains separate against supplied accreditor criteria.']
(out/'GRADE_6_HISTORY_SCOPE_AND_SEQUENCE.md').write_text('\n\n'.join(course)+'\n',encoding='utf-8')
for p in d['projects']:
 lines=[f"# {p['id']} — {p['title']}",f"Updated {d['date']}. {d['status']}",'[Course map](../GRADE_6_HISTORY_SCOPE_AND_SEQUENCE.md) · [Workbook](<../../6th Grade/Grade_6_History_Curriculum_Standards.xlsx>)',
 f"**Inquiry:** {p['question']}",f"**Student work:** {p['glance']}",f"**Final experience:** {p['product']}",'**Lasting understandings:** '+' '.join(p['understandings']),
 '**Schedule and access:** Four weeks, eight 90-minute blocks, individual then group weekly. No required homework. Plan captions/diagram descriptions, readable maps, vocabulary previews and equivalent oral/text response routes preserving historical reasoning. Physical investigation access must be arranged for H3.',
 '**Outline status:** These are Step 4 design specifications. Step 5 must select exact texts, verify interpretation-dependent standards roles and expand procedures/prompts, examples and support. The planning clock is 10 minutes retrieval/source reading, 20 explicit context/modeling, 35 project analysis, 15 private evidence and 10 feedback/handoff. This is a budget to test, not observed pacing. H3-W3-G uses the separately stated investigation budget.',
 '## Resources',links(p['resources']),'## Eight block outlines']
 for l in p['lessons']:
  lines += [f'<a id="{l["id"].lower()}"></a>\n### {l["id"]} — {l["title"]}',f"**Week {l['week']} / {l['mode']} / 90 minutes.**",f"**Learning and project contribution:** {l['content']}",f"**Resources:** {links(l['resources'])}. {l['reading']}",f"**Instruction/model to develop:** {l['model']}",f"**Planned activity:** {l['activity']}",f"**Individual evidence:** {l['evidence']}",f"**Quality criteria:** {l['criteria']}",f"**Feedback/support:** {l['support']}",f"**Preparation/handoff:** {l['handoff']}",f"**Builds on:** {l['prereq']}",f"**National roles:** Primary: {', '.join(l['primary'])}; Supporting: {', '.join(l['supporting']) or 'None separately assigned'}. NCSS themes: {', '.join('NCSS-T'+str(t) for t in l['themes'])}. {l['verification']}"]
 lines += ['## Next-stage production','Select and record exact creator, date, place, purpose, audience, provenance and excerpt boundaries. Prepare a model using different content, a developing response with feedback, a held-back source/map case and observable scoring guidance. Verify the busiest pair’s whole reading/modeling/analysis/evidence/feedback workload before completing detailed plans. Keep individual understanding separate from team product quality.']
 (plans/f"{p['slug']}.md").write_text('\n\n'.join(lines)+'\n',encoding='utf-8')
print('Published history course map and four project outline documents.')
