from pathlib import Path
import json
base=Path(__file__).resolve().parent;root=base.parents[1]
d=json.loads((base/'history.json').read_text(encoding='utf-8'))
out=root/'scope-and-sequence';plans=out/'history-projects';plans.mkdir(exist_ok=True)
res={r['id']:r for r in d['resources']}
def cell(v):return str(v).replace('|','/').replace('\n','<br>')
def table(h,rows):return '\n'.join(['| '+' | '.join(h)+' |','| '+' | '.join(['---']*len(h))+' |']+['| '+' | '.join(cell(v) for v in r)+' |' for r in rows])
def links(ids):return '; '.join(f"[{res[i]['title']}]({res[i]['url']})" for i in ids)
def ll(l,p):return f"[{l['id']}](history-projects/{p['slug']}.md#{l['id'].lower()})"
course=['# Grade 6 history scope and sequence',f"Updated {d['date']}. {d['status']}",
'## Course overview','Students investigate how societies formed, compare their institutions and beliefs, connect inventions with historical context, and explain Rome’s transformation using evidence.',
table(['Item','Plan'],[['Schedule',d['scope']],['National basis','NCSS National Curriculum Standards (2010), public ten-theme framework; C3 Framework (2013), selected Grades 6–8 indicators. Theme labels NCSS-T1–T10 are local navigation labels, not official performance codes.'],['Content allocation','Early humans and Mesopotamia → Egypt/Nubia, Israel and India → China and Greece → Rome through western collapse and eastern continuation. Societies overlap in time; the project order is not a single worldwide succession.'],['Tennessee check','2024 adoption / 2027–28 implementation. 62 content standards and six recurring practices routed; 6.39 chronology is Unverified and SSP.01 oral modality Conditional.'],['Workbook','[Grade 6 history workbook](<../6th Grade/Grade_6_History_Curriculum_Standards.xlsx>)'],['Input','[Completed Grade 6 handoff](<../6th Grade/Grade_6_Project_Handoff.md>); revised H3 is authoritative.'],['Outside work and enrollment','No required homework. Planning assumption: 24 learners/six teams; confirm actual calendar, learner needs and observation capacity.'],['Completion boundary','Steps 1–5 teacher planning is developed for all 32 blocks. Project documents contain procedures, models, prompts, assessment criteria, support and fitted clocks. Finished student packets and classroom trials remain Step 6.']]),
'## Projects at a glance',table(['Project','What students do','Final product / experience','Reading / resources','Assessments'],[[f"[{p['id']} {p['title']}](history-projects/{p['slug']}.md)",p['glance'],p['product'],'Short attributed context readings, dated maps and selected source cards; teacher sources in the register.','Private source/knowledge checks, revised individual explanation and a separately reviewed team product.'] for p in d['projects']]),
'## Progression and assessment',table(['Strand','Sequence'],[['Inquiry','Guided sourcing/inference → contextualized comparison → distinguish historical evidence and modern measurement → increasingly independent corroboration and multi-cause argument.'],['Geography and chronology','Local settlement map → overlapping society maps/timelines → separate China/Greece exchange networks → changing Roman boundaries and eastern continuation.'],['Institutions and economy','Surplus, specialization and city authority → social roles/belief institutions → philosophical/state support and citizenship → republic/empire, infrastructure and political/economic pressures.'],['Source reasoning','Maker/date/place/type → purpose/perspective and missing voices → evidence limits and transmission claims → competing interpretations and relative causes.'],['Assessment','Practice and drafts get specific feedback. Final individual responses and fresh-source checks establish each learner’s reasoning separately from group polish. No invented weights, scores or cutoffs.']])]
for p in d['projects']:
 course += [f"## {p['id']} — {p['title']}",f"**Question:** {p['question']}", '**Lasting understandings:** '+' '.join(p['understandings']),
 table(['Course week','Priority learning','Individual / group blocks','Evidence and feedback'],[[4*(p['n']-1)+w,p['lessons'][2*(w-1)]['content']+' '+p['lessons'][2*(w-1)+1]['content'],ll(p['lessons'][2*(w-1)],p)+': '+p['lessons'][2*(w-1)]['title']+'; '+ll(p['lessons'][2*(w-1)+1],p)+': '+p['lessons'][2*(w-1)+1]['title'],p['lessons'][2*(w-1)+1]['evidence']+' '+p['lessons'][2*(w-1)+1]['support']] for w in range(1,5)])]
course += ['## Workload review and next-stage decisions',
table(['Pair / issue','Planning correction','Still to verify'],[['H2-W3: India','Two short religion profiles plus a city plan/achievement strip. Caption polish moves to W4-I. Everyone studies all societies.','Two bounded profiles; 32 minutes project comparison and 10 minutes private component check. Trial actual reading fit in Step 6.'],['H3-W2: Greece','Short conflict/philosophy cards, reuse maps/timeline, one later water-timer investigation; no gear reconstruction.','Detailed 90-minute budgets allocate extra reading/model time and preserve 32 minutes project work. Trial the 180-minute pair; move polish before reducing learning.'],['H3-W3: timer','One teacher-prepared device, three short repeat trials, supplied shadow data, analysis and cleanup. No second practical investigation.','MacTutor context selected; three repeats with adult-prepared vessels and role rotation specified. Pilot actual kits; produce labeled shadow data.'],['H4 council','Evidence discussion about actual history, with individually recorded explanations; no outcome game.','Six teams × six minutes; four 45-second individual explanations per team plus private fresh-source response. Confirm actual enrollment.']]),
'## Assumptions and unresolved needs',table(['Area','Action'],d['needs']),
'## National framework and inquiry routes','These are selected contributions within an ancient-history term. The public NCSS themes organize content; the full middle-grades performance expectations are not individually certified. C3 indicators describe end-of-band capacities and guide recurring practice; this Grade 6 term does not claim the complete Grades 6–8 framework. Remaining modern civics/economics/geography and informed-action work needs schoolwide allocation.',
table(['Local theme label','NCSS theme','Specified learning destinations'],[[t['id'],t['title'],', '.join(t['routes'])] for t in d['themes']]),
table(['C3 indicator','Interpretive learning summary','Primary routes','Supporting routes'],[[n['id'],n['learning'],', '.join(n['primary_routes']) or 'Supporting only',', '.join(n['support_routes']) or 'None separately assigned'] for n in d['national']]),
'## Tennessee content-compliance appendix','The official content wording below is extracted from PDF pages 83–98; source PDF controls. SSP summaries are interpretive, recurring across the term. Covered in plan means detailed teaching and private prompt specifications exist; materials and observed component evidence remain to verify. It does not establish mastery, operating compliance or accreditation.',
table(['TN requirement/component','Lesson and individual evidence destinations','Status','Action'],[[t['id']+' — '+t['source_text'],', '.join(t['routes']),t['status'],t['action']] for t in d['tn']]),
'## Recovered assignment traceability',table(['Project','Recovered home IDs','Recurrence IDs','Interpretation'],[[p['id'],', '.join(f'SS.{i:02}' for i in p['home']),', '.join(f'SS.{i:02}' for i in p['recur']) or 'Prior-grade foundations','Historical bundled learning retained. These local IDs are not the official TN 6.xx or national identifiers. SSP.01–06 recur throughout.'] for p in d['projects']]),
'## Source and resource register',table(['Resource','Assigned use','Readiness'],[[f"{r['id']} — [{r['title']}]({r['url']})",r['selection'],r['status']] for r in d['resources']]),
'## Material-production handoff','Step 5 procedures, source-section selections, worked examples, private prompts, criteria and clocks now exist for every lesson. Step 6 produces and checks student packets, primary-object records, fresh cases and calibrated response keys; pilot the busiest pairs and timer kits. Keep 6.39 Unverified and the SSP.01 oral modality Conditional until resolved. Accreditation review remains separate.']
(out/'GRADE_6_HISTORY_SCOPE_AND_SEQUENCE.md').write_text('\n\n'.join(course)+'\n',encoding='utf-8')
for p in d['projects']:
 lines=[f"# {p['id']} — {p['title']}",f"Updated {d['date']}. {d['status']}",'[Course map](../GRADE_6_HISTORY_SCOPE_AND_SEQUENCE.md) · [Workbook](<../../6th Grade/Grade_6_History_Curriculum_Standards.xlsx>)',
 f"**Inquiry:** {p['question']}",f"**Student work:** {p['glance']}",f"**Final experience:** {p['product']}",'**Lasting understandings:** '+' '.join(p['understandings']),
 '**Schedule and access:** Four weeks, eight 90-minute blocks, individual then group weekly. No required homework. Plan captions/diagram descriptions, readable maps, vocabulary previews and equivalent oral/text response routes preserving historical reasoning. Physical investigation access must be arranged for H3.',
 '**Plan status:** Detailed Step 5 teacher plans; source adaptations and student packets remain Step 6. Each clock is a planning budget, not observed pacing. Collect private evidence separately from team product quality.',
 '## Resources',links(p['resources']),'## Eight detailed lesson plans']
 for l in p['lessons']:
  lines += [f'<a id="{l["id"].lower()}"></a>\n### {l["id"]} — {l["title"]}',f"**Week {l['week']} / {l['mode']} / 90 minutes.**",f"**Outcomes:** {' '.join(l['outcomes'])}",f"**Learning and project contribution:** {l['content']}",f"**Starting work:** {l['prereq']}",f"**Selected resources:** {links(l['resources'])}. {l['reading']}",f"**Direct section links:** {'; '.join('['+r['title']+']('+r['url']+')' for r in l['section_links']) or 'Reuse the previously attributed packet; fresh cases remain to produce.'}",f"**Source record:** {l['metadata']}",l.get('source_condition','Primary-object records and adaptation fit must be checked during material production.'),'#### Teacher procedure', '\n'.join(f"{i+1}. {v}" for i,v in enumerate(l['steps'])),f"**Explicit instruction:** {l['model']}",f"**Worked example / expected reasoning:** {l['worked_example']}",f"**Developing response and feedback:** {l['developing']}",f"**Student task directions:** {l['student_directions']}",f"**Project activity:** {l['activity']}",'#### Assessment and response to difficulty',f"**Private prompt:** {l['prompt']}",f"**Collect:** {l['evidence']}",f"**Evidence conditions:** {l['assessment_conditions']}",f"**Quality criteria:** {l['criteria']}",f"**Descriptive assessment:** {l['grading']}",f"**Difficulty and teacher response:** {l['support']}",f"**Different-example recheck:** {l['recheck']}",f"**Extension:** {l['extension']}",f"**Preparation:** {l['materials']}",f"**Next lesson handoff:** {l['handoff']}",'#### Teacher reference: clock and learning routes',table(['Minutes','Action'],[[a['minutes'],a['task']] for a in l['agenda']]),f"**Skills:** {l['skills']}",f"**National roles:** Primary: {', '.join(l['primary'])}; Supporting: {', '.join(l['supporting']) or 'None separately assigned'}. NCSS themes: {', '.join('NCSS-T'+str(t) for t in l['themes'])}. {l['verification']}",table(['Indicator / role','Teaching or deliberate review','Practice','Individual check / criterion','Verification'],[[r['id']+' / '+r['role'],r['teach'],r['practice'],r['check']+' '+r['criterion'],r['status']] for r in l['standards_routes']])]
 lines += ['## Build review',table(['Lesson / issue','Concrete correction','Evidence checked','Unresolved need'],[[l['id']+' / source, workload and assessment', 'Bounded selection, specific model, private prompt, fresh recheck and protected project work.', '90-minute agenda, individual evidence conditions and national contribution routes specified.',l.get('source_condition','Produce source adaptations/primary records and trial actual timing.')] for l in p['lessons']]),'## Step 6 production','Create the specified student texts/maps/cards, complete product example, held-back cases and calibrated response guidance. Preserve source metadata and unresolved chronology/oral-source flags. Trial actual reader and observation demands before calling the course classroom-ready.']
 (plans/f"{p['slug']}.md").write_text('\n\n'.join(lines)+'\n',encoding='utf-8')
print('Published history course map and four detailed project teaching documents.')
